[package]
name = "biodivine-lib-param-bn"
version = "0.3.0-SNAPSHOT"
authors = ["Samuel Pastva <daemontus@gmail.com>"]
edition = "2021"
description = "Library for working with parametrized Boolean networks."
homepage = "https://github.com/sybila/biodivine-lib-param-bn"
repository = "https://github.com/sybila/biodivine-lib-param-bn"
readme = "README.md"
keywords = ["boolean-network", "asynchronous", "symbolic", "graph", "systems-biology"]
categories = ["science", "simulation"]
license = "MIT"

[lib]
name = "biodivine_lib_param_bn"
path = "src/lib.rs"

[[bin]]
name = "dump-graph"
path = "src/bin/dump_graph.rs"

# Enable rich docs for some online docs autogen services.
[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", "docs-head.html"]

[features]
print-progress = []

[dependencies]
regex = "1.3.3"                 # Regexes used for parsing of basic .aeon constructs.
lazy_static = "1.4.0"           # Used for initialization of commonly used regexes.
biodivine-lib-bdd = { git = "https://github.com/sybila/biodivine-lib-bdd/" }
num-bigint = "0.4.3"            # Used as infinite-precision representation in BDDs.
num-traits = "0.2.15"           # `BigInt::to_f64`
roxmltree = "0.14.0"            # Used for SBML parsing.
bitvector = "0.1.5"             # Represents Boolean states of complex networks.
z3 = "0.11.2"

[dev-dependencies]
pretty_assertions = "0.6.1"